### ISSUE TITLE
小小的翻译错误

### ISSUE THREAD

**Issue by ENegatiVY** [wangx404/symbol_coding_tutorials_of_MXNet#1]
NDArray索引-数组索引功能
原文：示例： 想要通过高级索引从4x3的数组中挑选出位于边角的元素值，你需要选择位于[0, 2]行和[0, 3]列的元素。因此你需要通过高级索引指明这一点。通过上面解释的方法，你可以这样来写：

应该修改为：位于[0, 2]列和[0, 3]行的元素。

感谢翻译

**Comment by wangx404** [comment]
恩, 是搞错了.

这是哪一小节的呢?

**Comment by ENegatiVY** [comment]
> 恩, 是搞错了.
> 
> 这是哪一小节的呢?

00_basics下的01章下的纯整数数组索引小结
